export * from "@/components/description";
export * from "@/components/footer/footer";
export * from "@/components/header";
export * from "@/components/hero";
export * from "@/components/zoom-parallax";
export * from "@/components/placeholder";
export * from "@/components/nav"
export * from "@/components/image-section"
export * from "@/components/cuts"
export * from "@/components/preloader/pre-loader"